# Generated by Django 4.1 on 2022-08-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("fecha", models.DateField(auto_now_add=True)),
                ("imagen", models.ImageField(upload_to="proyectos/imagenes")),
                ("link", models.URLField(blank=True)),
            ],
        ),
    ]
