# Generated by Django 4.1 on 2022-08-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proyecto",
            name="imagen",
            field=models.ImageField(upload_to="proyectos/imagenes/"),
        ),
    ]
